http.host: 0.0.0.0

### x-pack functions
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: true
xpack.watcher.enabled: true

### http.cors setting
http.cors.allow-origin: "*"
http.cors.enabled: true
