version: '3'

services:
  redmine:
    build: redmine
    ports:
          - 3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: password
    depends_on:
      - db
    restart: always

  db:
    build: mysql
    user: "1000:50"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d/
      - ./mysql/scripts:/etc/mysql/scripts/
      - ./mysql/data:/var/lib/mysql

  splunk:
    build: splunk
    environment:
      SPLUNK_USER: root
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
    volumes:
      - ./splunk/etc:/opt/splunk/etc
      - ./splunk/var:/opt/splunk/var
    links:
      - db:mysql
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
    restart: always
