version: '2'

services:

  # == REDMINE ==========================
  redmine:
    build: redmine
    ports:
          - 80:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: password
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./redmine/script/elasticsearch:/usr/src/redmine/script/elasticsearch/
    hostname: redmine
    container_name: redmine

  # == Mysql ==========================
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d/
      - ./mysql/mysqldump:/docker-entrypoint-initdb.d
      - dbdata1:/var/lib/mysql
    hostname: mysql
    container_name: mysql

  # == Elasticsearch ==========================
  # mod host vm.max_map_count. https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker
  elasticsearch:
    build: elasticsearch
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - xpack.monitoring.history.duration=1d
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    links:
      - mysql:mysql
    ports:
      - 9200:9200
    expose:
      - 9300

  # == Kibana ==========================
  kibana:
    build: kibana
    container_name: kibana
    hostname: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_MONITORING_ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_SECURITY_ENABLED: "false"
    links:
        - elasticsearch:elasticsearch
    ports:
        - 5601:5601
    mem_limit: 2g
    memswap_limit: 2g
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  dbdata1:
    driver: local
  esdata1:
    driver: local

