version: '3'

services:

  # == REDMINE ==========================
  redmine:
    build: redmine
    ports:
          - 3000:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: password
    depends_on:
      - mysql
    restart: always
    hostname: redmine
    container_name: redmine

  # == Mysql ==========================
  mysql:
    build: mysql
    user: "1000:50"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d/
      - ./mysql/scripts:/etc/mysql/scripts/
      - ./mysql/data:/var/lib/mysql
    hostname: mysql
    container_name: mysql

  # == Elasticsearch ==========================
  elasticsearch:
    build: elasticsearch
    volumes:
      - ./elasticseatch/data:/usr/share/elasticsearch/data
      - ./elasticseatch/config:/usr/share/elasticsearch/config
      - ./elasticseatch/scripts:/usr/share/elasticsearch/scripts
    container_name: elasticsearch
    hostname: elasticsearch
    ulimits:
        nofile:
            soft: 65536
            hard: 65536
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    links:
      - mysql:mysql
    ports:
      - "9200:9200"
    expose:
      - "9300"

  # == Kibana ==========================
  kibana:
    build: kibana
    container_name: kibana
    hostname: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
        - elasticsearch:elasticsearch
    ports:
        - 80:5601

  # splunk:
  #   build: splunk
  #   environment:
  #     SPLUNK_USER: root
  #     SPLUNK_START_ARGS: --accept-license --answer-yes
  #     SPLUNK_ENABLE_LISTEN: 9997
  #     SPLUNK_ADD: tcp 1514
  #   volumes:
  #     - ./splunk/etc:/opt/splunk/etc
  #     - ./splunk/var:/opt/splunk/var
  #     - ./splunk/scripts:/opt/splunk/bin/scripts
  #   links:
  #     - db:mysql
  #   ports:
  #     - "8000:8000"
  #     - "9997:9997"
  #     - "8088:8088"
  #     - "1514:1514"
  #   restart: always
